// Diagnostics codes used by gw-ws-components
export const Codes = {
  PRECONDITION_REQUIRED: 'PRECONDITION_REQUIRED',
  PRECONDITION_INVALID: 'PRECONDITION_INVALID',
  ROUTER_HANDLER_ERROR: 'ROUTER_HANDLER_ERROR',
  ROUTER_UNKNOWN_SUBJECT: 'ROUTER_UNKNOWN_SUBJECT',
};
